--创建一个学生表，有4个字段，学生id，学生姓名，学生年纪，学生性别
CREATE TABLE STUDENT(
[SID] INT PRIMARY KEY IDENTITY,
[SNAME] NVARCHAR(30),
[SAGE] INT ,
[SSEX] BIT,
)
INSERT INTO STUDENT VALUES (N'李智博',24,1)
INSERT INTO STUDENT VALUES (N'刘伟',22,0)
INSERT INTO STUDENT VALUES (N'周丁浩',25,0)
INSERT INTO STUDENT VALUES (N'廖小帅',26,1)
INSERT INTO STUDENT VALUES (N'王正义',27,1)

SELECT *FROM STUDENT


--创建一个教师表 教师id，教师姓名，
CREATE TABLE TEACHER(
 [TID] INT PRIMARY KEY IDENTITY,
 [TNAME] NVARCHAR(30) ,

)


SELECT *FROM TEACHER;
INSERT TEACHER VALUES (N'飞哥')
INSERT TEACHER VALUES (N'小鱼')
INSERT TEACHER VALUES (N'王老师')
INSERT TEACHER VALUES (N'程老师')


----创建哦一个成绩表 ,主键字段SKEY，学生ID SID，课程id CID (COURSE课程)，学生成绩score
CREATE TABLE SC(
SKEY INT PRIMARY KEY IDENTITY,
[SID] NVARCHAR(30),
CID NVARCHAR(30),
SCORE INT ,
)
SELECT*FROM SC;

INSERT SC VALUES (1,2,90)
INSERT SC VALUES (3,4,60)
INSERT SC VALUES (2,5,80)
INSERT SC VALUES (4,2,95)

---创建一个一个课程表 CID （课程id），CNAME (课程名字)，TID(教师id) 
CREATE TABLE COURSE(
CID INT PRIMARY KEY IDENTITY,
CNAME NVARCHAR(30),
TID NVARCHAR(30),
)
SELECT*FROM COURSE;
INSERT COURSE VALUES (N'JAVA',1)
INSERT COURSE VALUES (N'SQL',2)
INSERT COURSE VALUES (N'HTML',3)
INSERT COURSE VALUES (N'CSS',4)


-----上面的4 个表建好了，求每门课程的学生人数
select COURSE.CNAME N'课程名称',count(*)N'人数' from SC,COURSE where SC.CId=COURSE.CId
GROUP BY SC.CId